### PR TITLE
0.6.6

### PR DESCRIPTION
**Pull request by loosebazooka**
This only has the change to read gcloud config.

### CODE REVIEW

**Comment by elharo** [comment]
This is interesting if unrelated:

[ERROR]   LibrariesTest.testVersionExists:175->assertReachable:117 Could not reach https://repo1.maven.org/maven2/com/google/cloud/google-cloud-bigquery/1.41.0/ expected:<200> but was:<403>

I wonder what's going on here?

**Comment by loosebazooka** [comment]
@elharo, yeah I saw it on some other tests (from travis specifically), I've restarted the test anyway.

**Comment by loosebazooka** [comment]
@elharo more details, it appears like some kind of weird config issue, but I can't tell:
https://travis-ci.org/GoogleCloudPlatform/appengine-plugins-core/builds/422363884#L456
```
HTTP/1.1 403 Forbidden
Server: Varnish
Retry-After: 0
Content-Type: text/html; charset=utf-8
Content-Length: 421
Accept-Ranges: bytes
Date: Thu, 30 Aug 2018 03:03:27 GMT
Via: 1.1 varnish
Connection: close
X-Served-By: cache-jfk8132-JFK
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1535598207.366761,VS0,VE0
```

**Comment by loosebazooka** [comment]
@elharo disabling the requirement on travis for now.

**Comment by elharo** [comment]
My guess is that Maven central doesn't like our user agent or the host we're connecting from or some such.

**Comment by briandealwis** [comment]
Travis seems happy now.

**Comment by loosebazooka** [comment]
@elharo possible reason: https://github.com/travis-ci/travis-ci/issues/10055

**Pull request merged**
