### PR TITLE
Remove deprecated compute api from libraries.json

### PR DESCRIPTION
**Pull request by loosebazooka**
For whatever reason, this compute api is deprecated : details at https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2732

Offline discussion was to just remove this. Also I removed a bunch of trailing white spaces from this file.

### CODE REVIEW

**Comment by patflynn** [comment]
seems like the list should be updated to use whatever the new non-deprecated compute client is.

**Comment by loosebazooka** [comment]
It does not appear like there is a non-deprecated one.

**Comment by patflynn** [comment]
@garrettjonesgoogle what is the correct compute API for Java?

**Comment by garrettjonesgoogle** [comment]
There is not a non-deprecated one yet. We are working on it - it will be a month or two.

**Pull request merged**
