### PR TITLE
Use appengine-plugins-core in URLs

### PR DESCRIPTION
**Pull request by elharo**
@meltsufin

### CODE REVIEW

**Comment by meltsufin** [comment]
Yes! Thank you.
:ship:

**Comment by elharo** [comment]
@meltsufin Merged

**Comment by chanseokoh** [comment]
I see this is not merged.

**Comment by elharo** [comment]
🚢 == LGTM

**Comment by meltsufin** [comment]
:ship: :shipit: :rocket: :bike: :runner: = LGTM

**Pull request merged**
