### PR TITLE
Release 0.3.8

### PR DESCRIPTION
**Pull request by elharo**
@loosebazooka @chanseokoh @coollog

### CODE REVIEW

**Comment by loosebazooka** [comment]
I don't fully understand why we need this resource directory in the source directory? see : https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/463/files

**Comment by chanseokoh** [comment]
@loosebazooka I agree that the JSON is not a Java source file, so it shouldn't be under `src/main/java`. (Anyway, it has been like that for a while.)

**Comment by elharo** [comment]
It doesn't have to be under src/main/java. It can be there, however. Eclipse projects, for example, put numerous non-Java files directly into their package directories. It's a little easier to edit things if all the related files are together rather than in separate trees.

**Comment by chanseokoh** [comment]
There are also some downsides.
- The directory is deep inside the directory hierarchy. It's easy to forget it's a resource directory. If we start adding resource directories in this fashion, we may lose track easily.
- But more importantly, this prevents creating Java packages with the prefix of `com/google/cloud/tools/libraries`. I did some testing, and looks like anything put under `src/main/java/com/google/cloud/tools/libraries` (including `.java` files and subdirectories) will be packaged into the final JAR.

**Comment by elharo** [comment]
@chanseokoh's last comment is convincing. That said, that is a separate issue which I've filed as #467.

Unless you think the code is currently broken or that the external interface will change (i.e. the path by which we'll load the resource will be different), that should not block us from moving forward with this PR.

**Comment by chanseokoh** [comment]
Need to merge with master.

**Comment by loosebazooka** [comment]
I would probably kill this PR, delete the tag, and remake with a new one.

**Pull request closed without merging**
