### PR TITLE
preparing release 0.3.7

### PR DESCRIPTION
**Pull request by elharo**
@loosebazooka @coollog

### CODE REVIEW

**Comment by loosebazooka** [comment]
Did you figure out how to unstuck a CLA thing?

**Comment by loosebazooka** [comment]
@elharo, we've been doing releases as a set of commits in the style of this : https://github.com/GoogleCloudPlatform/app-gradle-plugin/pull/166

**Comment by elharo** [comment]
To unstick the CLA add the PR to this bug: https://b.corp.google.com/issues/67016237

**Comment by elharo** [comment]
PTAL @loosebazooka

**Comment by elharo** [comment]
Ping

**Pull request merged**
