### PR TITLE
Tests : Wait for stderr listener to complete

### PR DESCRIPTION
**Pull request by loosebazooka**

### CODE REVIEW

**Comment by loosebazooka** [comment]
@meltsufin should fix that test..

**Comment by meltsufin** [comment]
Do we understand why this is happening? What's the rationale for 1000ms wait vs. some other number?

**Comment by loosebazooka** [comment]
It's because the test thread ends before the "stderr" reading thread ends. It's a race condition in the test specifically. In normal use, stderr reading would just continue until it finishes writing to some console or window.

**Comment by loosebazooka** [comment]
as for 1000 vs any other number, no real reason. I think 1000 is safe for this test though.

**Comment by loosebazooka** [comment]
tests were also in the wrong package, so I moved those.

**Pull request closed without merging**
