### PR TITLE
Fix test failures: LibrariesTest and ManagedCloudSdkTest

### LINKED ISSUE #822: LibrariesTest fail to verify https://dialogflow.com
Currently all tests are suddenly failing with the following error:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 51.686 s <<< FAILURE! - in com.google.cloud.tools.libraries.LibrariesTest
[ERROR] testJson(com.google.cloud.tools.libraries.LibrariesTest)  Time elapsed: 51.638 s  <<< ERROR!
java.net.ProtocolException: Server redirected too many  times (20)
        at com.google.cloud.tools.libraries.LibrariesTest.assertReachable(LibrariesTest.java:128)
        at com.google.cloud.tools.libraries.LibrariesTest.assertApi(LibrariesTest.java:88)
        at com.google.cloud.tools.libraries.LibrariesTest.testJson(LibrariesTest.java:69)
```

Turns out `HttpURLConnection` always fails to connect to  `dialogflow.com`.

```java
// This always fails.
((HttpURLConnection) new URL("https://dialogflow.com").openConnection()).getResponseCode();
```

I figured out it does multiple complex redirections bouncing back and forth between dialogflow.com and accounts.google.com. And the redirection never ends successfully without setting cookies required by the servers. Fortunately, there's a simple way to enable automatic cookie managing.

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #822.

Hopefully this also fixes https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/818#issuecomment-578885673.

### CODE REVIEW

**Comment by etanshaul** [comment]
in the referenced PR, the test that is failing is `testManagedCloudSdk_latest()` (not the fixed version). Does this still somehow address that?

**Comment by chanseokoh** [comment]
`testManagedCloudSdk_latest()` downgrades to `FIXED_VERSION` and then to latest. So, hopefully, yes, but I haven't actually verified yet.

**Comment by chanseokoh** [comment]
Got a different error with version 272. :(

```
'DO' is not recognized as an internal or external command,
operable program or batch file.
( was unexpected at this time.

[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 227.578 s <<< FAILURE! - in com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest
[ERROR] testManagedCloudSdk_latest(com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest)  Time elapsed: 155.422 s  <<< ERROR!
com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 255
	at com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest.testManagedCloudSdk_latest(ManagedCloudSdkTest.java:128)
```

**Comment by etanshaul** [comment]
any reason you are using 272 and not the latest 277? maybe worth trying that one?

**Comment by chanseokoh** [comment]
FIXED_VERSION should be behind latest in order for the downgrading test to work, so I'm now testing 276. I was hoping that recent gcloud versions work well with both Python 2 or 3, but it it still fails, we need to investigate further.

**Comment by chanseokoh** [comment]
Tests are passing. Looks like 276 works for Windows.

(Coincidentally, Maven Central and gcloud has been very flaky today.)

**Pull request merged**
