### PR TITLE
Update maven-surefire-plugin to allow excluding tests

### PR DESCRIPTION
**Pull request by briandealwis**
Some tests take a while and it would be nice to be able to be able to exclude them for faster turnaround.  maven-surefire-plugin 2.19 or later supports a bang notation:
```
$ mvn -Dtest='!ManagedCloudSdkTest' verify
```

The two I've found useful:
  - `ManagedCloudSdkTest`: if no Cloud SDK is available (e.g., running tests from a scratch docker instance), this test downloads and installs the Cloud SDK
  - `LibrariesTest`: does a whole series of network calls

### CODE REVIEW

**Comment by chanseokoh** [comment]
> `$ mvn -Dtest='!ManagedCloudSdkTest' verify`

Out of curiosity, no need to give fully qualified names to `-Dtest`?

**Comment by briandealwis** [comment]
From the [doc](http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#test):
> Each pattern you specify here will be used to create an include pattern formatted like **/${test}.java, so you can just type -Dtest=MyTest to run a single test called "foo/MyTest.java".

2.21.0 supports ANSI colour. Whee!

**Comment by briandealwis** [comment]
These errors are funnily enough caused by `ManagedCloudSdkTest`:
```
testManagedCloudSdk_latest(com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest)
Welcome to the Google Cloud SDK!
Your current Cloud SDK version is: 205.0.0
Installing components from version: 204.0.0
+-------------------------------------------------+
|        These components will be updated.        |
[…]
ERROR: (gcloud.components.update) The component [bq] failed to download.
<urlopen error [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib>
This will install all the core command line tools necessary for working with
the Google Cloud Platform.
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 28.489 s <<< FAILURE! - in com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest
[ERROR] testManagedCloudSdk_latest(com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest)  Time elapsed: 3.389 s  <<< ERROR!
com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 1
	at com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest.testManagedCloudSdk_latest(ManagedCloudSdkTest.java:117)
```

**Comment by chanseokoh** [comment]
The errors won't go away until #667 is merged.

**Pull request merged**
