### PR TITLE
[do not merge] check adding -E flag in build script

### PR DESCRIPTION
**Pull request by emmileaf**
For troubleshooting release script / Kokoro environment compatibility

### CODE REVIEW

**Comment by emmileaf** [comment]
FYI @lqiu96 - let's see if the `kokoro-ubuntu` check gets stuck on the same issue as the release script?

**Comment by lqiu96** [comment]
> FYI @lqiu96 - let's see if the `kokoro-ubuntu` check gets stuck on the same issue as the release script?

Thanks @emmileaf. I think `kokoro-ubuntu` runs the this job: https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/kokoro/continuous.sh, right? The PR I just submitted passed that CI job so I think it's probably the additional `-E` flags in the release script causing the issue.

**Comment by lqiu96** [comment]
Not entirely sure why it was added in the first place or why it was only added to only the release job. I'll do a bit of digging before I just remove this flag.

**Comment by lqiu96** [comment]
Ok, nvm. I misunderstood the PR. This still passes even with the `-E` flag added into the continuous script. That's odd...

**Comment by emmileaf** [comment]
> This still passes even with the `-E` flag added into the continuous script. That's odd...

Yeah this is just a sanity check to see if the issue can be reproduced on the continuous script, but seems not...could it have been a one-time/transient thing?

**Comment by lqiu96** [comment]
> > This still passes even with the `-E` flag added into the continuous script. That's odd...
> 
> Yeah this is just a sanity check to see if the issue can be reproduced on the continuous script, but seems not...could it have been a one-time/transient thing?  

Tried re-running the job and it's the same issue. Stuck waiting for user input unfortunately.

**Pull request closed without merging**
