### PR TITLE
chore: Use mvn instead of mvnw

### PR DESCRIPTION
**Pull request by lqiu96**

### CODE REVIEW

**Review by emmileaf — APPROVED** [review]
LGTM - dropping a backlink to https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/923 for context

**Review by meltsufin — APPROVED** [review]
Let's remove the wrapper then. Same for spring-cloud-gcp. CC: @emmileaf.

**Comment by lqiu96** [comment]
I'll remove the maven wrapper in a separate PR. Going to try and see if this fixes the release.

**Comment by lqiu96** [comment]
FYI, there is an issue prevent the release: https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/925. I'll need to investigate so more.

**Pull request merged**
