### PR TITLE
Update cloud sdk test version to a more recent one

### LINKED ISSUE #786: Upgrading cloud sdk 178.0.0 to LATEST throws errors in tests
```
ERROR: gcloud crashed (SSLHandshakeError): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
```
@vilasj FYI

### PR DESCRIPTION
**Pull request by loosebazooka**
fixes #786

### CODE REVIEW

**Comment by loosebazooka** [comment]
@elharo can you file a bug against the cloud sdk then?

**Comment by loosebazooka** [comment]
Can you file a bug against the cloud sdk. We can leave the bug open but I think we should fix our build for now.

**Comment by elharo** [comment]
https://b.corp.google.com/issues/130662376

but we need to do a little more. Who's the relevant person in Cloud SDK right now? We need to ping them and get this looked into.

**Comment by elharo** [comment]
I'm still getting failures in this test:

[ERROR] Tests run: 8, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 34.587 s <<< FAILURE! - in com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest
[ERROR] testManagedCloudSdk_fixedVersion(com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest)  Time elapsed: 4.538 s  <<< ERROR!
com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 1
	at com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest.testManagedCloudSdk_fixedVersion(ManagedCloudSdkTest.java:91)

[ERROR] testManagedCloudSdk_latest(com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest)  Time elapsed: 30.035 s  <<< ERROR!
com.google.cloud.tools.managedcloudsdk.ManagedSdkVerificationException: com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 1
	at com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest.testManagedCloudSdk_latest(ManagedCloudSdkTest.java:126)
Caused by: com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 1
	at com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest.testManagedCloudSdk_latest(ManagedCloudSdkTest.java:126)

**Pull request merged**
