### PR TITLE
copy DeleteAllVisitor to appengine-plugins-core and add tests

### PR DESCRIPTION
**Pull request by elharo**
@loosebazooka

### CODE REVIEW

**Comment by elharo** [comment]
Ping

**Comment by elharo** [comment]
Ping ping ping

**Comment by loosebazooka** [comment]
where is this used?

**Comment by elharo** [comment]
In Cloud Tools for Eclipse

**Comment by loosebazooka** [comment]
I wonder if we should be extending the appengine-plugin library to implement utilities that are not appengine related. Obviously this is a philosophical issue about the purpose of the library, and there is likely to be a difference in how people see it, but personally I'd rather not see generic file operations implemented in the library for use outside of it.

For example in Java9 I would like FileUtil to be not exported out of the module.

**Comment by patflynn** [comment]
+1. I agree with this mainly because the different target client platforms
diverge signicantly (maven vs gradle vs intellij vs eclipse) in terms of
Java language level, available libraries, and dependency requirements
(things like IJ standardizing on a version of Guava).  The core app-engine
is so important across those plugins that I want to keep it's scope as
narrow as possible.

**Pull request closed without merging**
