### PR TITLE
Better handling of invalid paths

### PR DESCRIPTION
**Pull request by elharo**
@loosebazooka @lesv and fix up the owners for the commit log

### CODE REVIEW

**Comment by loosebazooka** [comment]
Looks like it might be checkstyle. Use `mvn verify` instead of `mvn test` ?

**Comment by loosebazooka** [comment]
Lemme check the macos configs to see what we're doing. Maybe they updated the macos images and we're not configured correctly anymore.

**Comment by loosebazooka** [comment]
Hey, I'm gone all next week, perhaps @chanseokoh can do the follow ups on this PR if any are required.

**Comment by elharo** [comment]
OK, I expect at least one more PR on this issue so I'll send that to @chanseokoh

**Pull request merged**
