### PR TITLE
Add minikube and skaffold to list of gcloud components

### PR DESCRIPTION
**Pull request by etanshaul**
gcloud now manages these extra components. Cloud Code is going to migrate to using the gcloud managed versions of these instead of using its own management system.

### CODE REVIEW

**Comment by etanshaul** [comment]
`gcloud components list`:
image

**Comment by chanseokoh** [comment]
There's a Kokoro-windows build failure. Not sure if it's a flaky one.

**Comment by etanshaul** [comment]
triggered a rebuild. Let's see

**Comment by etanshaul** [comment]
> Very interesting to see minikube. Hopefully we are now finally reached the state where installing minikube is as easy as gcloud components install minikube?

Yes that is the goal. There could still be some friction involved with hypervisor setup and so on, but Minikube has been making strides in simplifying this process.

**Comment by etanshaul** [comment]
hmm I think the test failure is because of the python changes to cloud sdk:

```
To use the Google Cloud SDK, you must have Python installed and on your PATH.
As an alternative, you may also set the CLOUDSDK_PYTHON environment variable
to the location of your Python executable.
c:\python27\python.exe: can't open file '!CLOUDSDK_PYTHON_ARGS_NO_S!': [Errno 2] No such file or directory
```

**Pull request merged**
