### PR TITLE
Upgrades the javac version to 1.8

### PR DESCRIPTION
**Pull request by nkibler**
**Context:** I'm about submit a PR for review that adds some utilities around the `libraries.json` file that contains metadata on Cloud API libraries. It'd be nice to use some Java 8 features in it (namely `Streams`).

### CODE REVIEW

**Comment by loosebazooka** [comment]
This isn't a terrible idea. Gradle 5.0 wont run on java 7.  Appengine java
8 is GA.

On Oct 5, 2017 19:46, "codecov[bot]" <notifications@github.com> wrote:

Codecov
<https://codecov.io/gh/GoogleCloudPlatform/appengine-plugins-core/pull/474?src=pr&el=h1>
Report

Merging #474
<https://codecov.io/gh/GoogleCloudPlatform/appengine-plugins-core/pull/474?src=pr&el=desc>
into master
<https://codecov.io/gh/GoogleCloudPlatform/appengine-plugins-core/commit/7b2c75d3bcf70d6fbb8939aab4d1fb56dec526a4?src=pr&el=desc>
will *not change* coverage.
The diff coverage is n/a.

[image: Impacted file tree graph]
<https://codecov.io/gh/GoogleCloudPlatform/appengine-plugins-core/pull/474?src=pr&el=tree>

@@           Coverage Diff           @@##           master     #474   +/-   ##
=======================================
  Coverage   67.05%   67.05%
=======================================
  Files          75       75
  Lines        1988     1988
  Branches      324      324
=======================================
  Hits         1333     1333
  Misses        513      513
  Partials      142      142

------------------------------

Continue to review full report at Codecov
<https://codecov.io/gh/GoogleCloudPlatform/appengine-plugins-core/pull/474?src=pr&el=continue>
.

*Legend* - Click here to learn more
<https://docs.codecov.io/docs/codecov-delta>
Δ = absolute <relative> (impact), ø = not affected, ? = missing data
Powered by Codecov
<https://codecov.io/gh/GoogleCloudPlatform/appengine-plugins-core/pull/474?src=pr&el=footer>.
Last update 7b2c75d...74a7409
<https://codecov.io/gh/GoogleCloudPlatform/appengine-plugins-core/pull/474?src=pr&el=lastupdated>.
Read the comment docs <https://docs.codecov.io/docs/pull-request-comments>.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/474#issuecomment-334621972>,
or mute the thread

**Comment by nkibler** [comment]
I'll move my code to the IntelliJ plugin, then, since it sounds like Eclipse has its own implementation and won't benefit from it. Meanwhile, I'll leave this PR open because we'll want to upgrade the source eventually anyway. You can merge this in when CT4E migrates to Java 8.

**Comment by briandealwis** [comment]
This won't break Eclipse per se, but we're supporting Eclipse Mars (4.5) which still runs on Java 7.  I wonder if we have any stats of the JVM versions being used for CT4E…

**Comment by nkibler** [comment]
I guess I could change this to target 7, but with an 8 source. It should allow for 8 features like Streams, but will likely disallow features that don't have a 7 bytecode analog (like default methods in interfaces). WDYT?

**Comment by etanshaul** [comment]
on second thought isn't that disallowed by the java compiler (source 8 with target 7?

**Comment by loosebazooka** [comment]
I think we should at least check if we need to keep supporting mars, given that Eclipse has already released Neon+Oxygen and is on Photon.

Would rather not be involved in java version shenanigans.

**Comment by elharo** [comment]
There are a lot of old Eclipse versions out in the wild. For comparison, we get GPE bug reports going back at least as far as 4.2. At some point, we will drop Mars support; but I don't want to do that until it buys us something really significant.

**Comment by nkibler** [comment]
I'll leave this up to you to do in the future then.

**Comment by loosebazooka** [comment]
@elharo @chanseokoh @briandealwis can we get some timeline on this?

**Comment by elharo** [comment]
There's no rush to do this. We can revisit when there's a compelling use case for Java 8 or dropping Eclipse Mars.

**Pull request closed without merging**
