### PR TITLE
remove libraries.json and related classes.

### PR DESCRIPTION
**Pull request by zhumin8**
As per separate discussion, removing `libraries.json` and related classes that's not used anymore.

### CODE REVIEW

**Review by loosebazooka — APPROVED** [review]
I know I'm not working on this project anymore, but I love a good PR with only deletions.

**Review by elefeint — APPROVED** [review]

**Comment by chanseokoh** [comment]
Not sure if you missed my message in the email thread, but the file is being used by CT4E.

**Comment by elefeint** [comment]
I did miss it :( I was hoping CT4E was also using DRIFT metadata, as is proper. I'll look into it.

**Comment by loosebazooka** [comment]
does CT4E still have an owner?

**Comment by elefeint** [comment]
@zhumin8 Unfortunately, it meas we'll have to fix up the broken links and leave the metadata for now. Or else, redo the Eclipse tool to use DRIFT, which is likely more work.

**Comment by elefeint** [comment]
@loosebazooka @briandealwis Cloud Java owns CT4E, so I am it, technically.

**Pull request closed without merging**
